---
# Description of aws ec2 instance

ami: ami-a4dc46db
init: None
role: arn:aws:iam::400029180276:instance-profile/swarm_access
region: us-east-1a
type: t2.micro
securityId: ['sg-9569addf', 'sg-eade92a1']
key: DLNAkey
securityGroup: ['HTTP_HTTPS', 'SSH']
name: create_user_service
